# Generated by Django 6.1 on 2026-08-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='flan',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=10000, max_digits=6),
        ),
    ]
